services:
  - type: web
    name: flask-docker-app
    env: docker
    repo: https://github.com/Hmzask/PRAIME-AI
    region: oregon
    plan: free
     envVars:
      - key: DATABASE_URL
      - key: CLIENT_SECRET
      - key: CLIENT_ID
      - key: API_KEY
       